### PR TITLE
Avatar badge components

### PR DESCRIPTION
**Pull request by gadgetfather**
I have created badge and avatar. please check and give feedback !

### CODE REVIEW

**Comment by AnkurChunekar** [comment]
Great work!, both badge and avatar, code is well formatted and comments are properly used!

**Review by NagaSatyaGeeth — APPROVED** [review]
neatly written code, looks great!

**Comment by Husain01** [comment]
Nice naming done for the CSS classes. Overall looks great.

**Comment by Kevin-Solomon** [comment]
Looks amazing akshay!!

**Comment by Abhijeet43** [comment]
Every thing seems fine... Great job akshay!!!!

**Review by starver20 — APPROVED** [review]
Well documented code.

**Pull request closed without merging**
